const AllProductArr = [
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
];
const categoryArr = [
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
  {
    discount: '-37%',
    img: '/assets/images/Frame28.png',
    name: 'Sponsored',
    name1: 'Act of war',
    price: '$13.99',
    button: 'Add to Cart',
  },
];
export { AllProductArr, categoryArr };
