const cheatstore = [
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
  {
    img: '/assets/icons/game_5966367.png',
    name: 'Pixel Pioneers',
    para: 'Innovators in immersive Storytelling',
    button: 'View Shop',
    star: '⭐⭐⭐⭐⭐',
  },
];
export { cheatstore };
